apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dpl
  namespace: esmns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esmprod
  template:
    metadata:
      labels:
        app: esmprod
    spec:
      containers:
        - name: esm_prod_con1
          image: murtaza0318/emsapp-backend:v14   # update with your image tag
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET